# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'captchify.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Captchify(object):
    def setupUi(self, Captchify):
        Captchify.setObjectName("Captchify")
        Captchify.resize(500, 363)
        Captchify.setMaximumSize(QtCore.QSize(500, 900))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/captchify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Captchify.setWindowIcon(icon)
        self.tab_widget = QtWidgets.QTabWidget(Captchify)
        self.tab_widget.setEnabled(True)
        self.tab_widget.setGeometry(QtCore.QRect(0, 0, 500, 471))
        self.tab_widget.setObjectName("tab_widget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 491, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(50, 10, 50, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.model_form_layout = QtWidgets.QFormLayout()
        self.model_form_layout.setObjectName("model_form_layout")
        self.model_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.model_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.model_label.setIndent(-1)
        self.model_label.setObjectName("model_label")
        self.model_form_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.model_label)
        self.model_combo_box = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model_combo_box.sizePolicy().hasHeightForWidth())
        self.model_combo_box.setSizePolicy(sizePolicy)
        self.model_combo_box.setToolTip("")
        self.model_combo_box.setObjectName("model_combo_box")
        self.model_form_layout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.model_combo_box)
        self.verticalLayout.addLayout(self.model_form_layout)
        self.captcha_vertical_layout = QtWidgets.QVBoxLayout()
        self.captcha_vertical_layout.setObjectName("captcha_vertical_layout")
        self.captcha_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.captcha_label.setObjectName("captcha_label")
        self.captcha_vertical_layout.addWidget(self.captcha_label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(44, -1, 44, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.single_solve_radio = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.single_solve_radio.setChecked(True)
        self.single_solve_radio.setObjectName("single_solve_radio")
        self.horizontalLayout_3.addWidget(self.single_solve_radio)
        self.multi_solve_radio = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.multi_solve_radio.setObjectName("multi_solve_radio")
        self.horizontalLayout_3.addWidget(self.multi_solve_radio)
        self.captcha_vertical_layout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.captcha_image_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.captcha_image_label.setMaximumSize(QtCore.QSize(290, 80))
        self.captcha_image_label.setObjectName("captcha_image_label")
        self.horizontalLayout.addWidget(self.captcha_image_label)
        self.captcha_vertical_layout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(44, -1, 44, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.captcha_image_file_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.captcha_image_file_label.setMaximumSize(QtCore.QSize(248, 16777215))
        self.captcha_image_file_label.setObjectName("captcha_image_file_label")
        self.horizontalLayout_2.addWidget(self.captcha_image_file_label)
        self.captcha_image_folder_button = QtWidgets.QToolButton(self.verticalLayoutWidget)
        self.captcha_image_folder_button.setShortcut("")
        self.captcha_image_folder_button.setObjectName("captcha_image_folder_button")
        self.horizontalLayout_2.addWidget(self.captcha_image_folder_button)
        self.captcha_vertical_layout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.captcha_vertical_layout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, 5, -1, -1)
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.solution_line_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.solution_line_edit.setEnabled(True)
        self.solution_line_edit.setReadOnly(True)
        self.solution_line_edit.setObjectName("solution_line_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.solution_line_edit)
        self.solution_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.solution_label.setObjectName("solution_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.solution_label)
        self.verticalLayout.addLayout(self.formLayout)
        self.tab_widget.addTab(self.tab, "")

        self.retranslateUi(Captchify)
        self.tab_widget.setCurrentIndex(0)
        self.single_solve_radio.toggled['bool'].connect(Captchify.set_mode)
        self.captcha_image_folder_button.released.connect(Captchify.open_file_dialog)
        self.model_combo_box.currentIndexChanged['int'].connect(Captchify.change_model)
        QtCore.QMetaObject.connectSlotsByName(Captchify)

    def retranslateUi(self, Captchify):
        _translate = QtCore.QCoreApplication.translate
        Captchify.setWindowTitle(_translate("Captchify", "Captchify"))
        self.model_label.setText(_translate("Captchify", "Model"))
        self.captcha_label.setText(_translate("Captchify", "Captcha to solve"))
        self.single_solve_radio.setToolTip(_translate("Captchify", "A solution will be displayed"))
        self.single_solve_radio.setText(_translate("Captchify", "Sing&le"))
        self.multi_solve_radio.setToolTip(_translate("Captchify", "The name of the images will be the solution"))
        self.multi_solve_radio.setText(_translate("Captchify", "M&ulti"))
        self.captcha_image_label.setText(_translate("Captchify", "<html><head/><body><p><img src=\":/images/aggs.jpg\"/></p></body></html>"))
        self.captcha_image_file_label.setText(_translate("Captchify", "img4893743.png"))
        self.captcha_image_folder_button.setToolTip(_translate("Captchify", "Open new captcha image"))
        self.captcha_image_folder_button.setStatusTip(_translate("Captchify", "Open new captcha image"))
        self.captcha_image_folder_button.setText(_translate("Captchify", "..."))
        self.solution_line_edit.setText(_translate("Captchify", "aggs"))
        self.solution_label.setText(_translate("Captchify", "Solution"))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("Captchify", "Captcha"))


import gui.resources_rc
